#!/usr/bin/env bash

set -euf -o pipefail

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
. $SCRIPTPATH/../bash/aliases
_dockerRun -v $(pwd):/repo registry.gitlab.com/fdroid/docker-executable-fdroidserver:latest "$@"
