#!/usr/bin/env bash

set -euf -o pipefail

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
. $SCRIPTPATH/../bash/aliases
_dockerRun -v "$(pwd)/:/usr/local/src/your-app" --env "CHANGELOG_GITHUB_TOKEN=$GITHUB_TOKEN" "garykim/gcg-fork" "$@"
