#!/usr/bin/env bash

set -euf -o pipefail

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
. $SCRIPTPATH/../bash/aliases
_dockerRun --entrypoint=manim --workdir /tmp/workdir -v "$(pwd)/:/tmp/workdir" "garykim/manim:latest" --media_dir=/tmp/workdir "$@"
